- name: common
  hosts: all
  become: yes
  roles:
    - name: common
#Setup front-end load balancer tier


- name: setup frontends
  hosts: frontends
  become: yes
  roles:
    - name: frontend

#Setup application servers tier

- name: apptiers
  hosts: apps
  become: yes
  roles:
    - name: app-tier

#Setup database tier

- name: setup db-tier
  become: yes
  hosts: appdbs
  roles:
    - name: db-tier
