- name: install postgres
  yum:
    name: postgresql-server
    state: latest
- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes
- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"

- name: Check PostgreSQL initialized.
  stat:
    path: "/var/lib/pgsql/data/PG_VERSION"
  register: pgver

#only run the next 2 tasks once!
- name: initilize postgres
  command: postgresql-setup initdb
  when: not pgver.stat.exists
- name: initilize postgres some more
  command: chkconfig postgresql on
- name: start postgres
  service:
    name: postgresql.service
    state: started
